### ISSUE TITLE
The method of candidate entity retrieval

### ISSUE THREAD

**Issue by season1blue** [ict-bigdatalab/VNEL#1]
Thanks for your work!
I wonder the method of candidate retrieval. Is the candidate entity obtained by calculating the similarity between the input image and the entity image?

**Comment by sunwenxiang** [comment]
Thank you for your attention!
In the benchmark experiment, in V2VEL(Vision-to-Vision), we calculate the simialry between the input image and the entity image. However, in V2TEL(Vision-to-Text), we calculate the simialry between the input image and the entity text. Besides, the similarity is calculated by the inner product of the embedding generated by different Encoders.
